blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from post.views import home,post_index,blog,listing
from django.conf import settings 


from django.conf.urls.static import static 


urlpatterns = [
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', post_index, name="home"),
    url(r'^/blog', listing, name="blogpage"),
    url(r'post/', include('post.urls', namespace="blog")),
    url(r'accounts/', include('accounts.urls', namespace="accounts")),
    url(r'elan/', include('elan.urls', namespace="elanlar")),
  
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elan/urls.py
from django.conf.urls import include, url
from .views import *
from django.conf import settings 
from django.conf.urls.static import static 
app_name = "elan"
urlpatterns = [
   
    
    url(r'^main/',elan, name="main" ),
    url(r'^(?P<id>\d+)/$', elandetail, name="elandetail" ),
    url(r'^elanlar/', store, name="store" ),
    url(r'^kids/', kids, name="kids" ),
    url(r'^work/', work, name="work" ),
    url(r'^service/', service, name="service" ),
    url(r'^personal/', personal, name="personal" ),
    url(r'^apartment/', apart, name="apart" ),
    url(r'^education/', education, name="edu" ),
    url(r'^elanadmin/', elanadmin, name="elanadmin" ),
    url(r'^(?P<id>\d+)/update/$', elan_update, name="elanupdate" ),
    url(r'^(?P<id>\d+)/delete/$', elan_delete, name="elandelete" ),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import include, url
from .views import home,post_index,post_detail,adminpost,post_create,post_update,post_delete,contact
from django.conf import settings 
from django.conf.urls.static import static 
app_name = "blog"
urlpatterns = [
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^contact/', contact, name="index"),
    url(r'^(?P<id>\d+)/$', post_detail, name="detail" ),
    url(r'^dashboard/', adminpost, name="dashboard"),
    url(r'^create/', post_create, name="create"),
    url(r'^(?P<id>\d+)/update/$', post_update, name="update" ),
    url(r'^(?P<id>\d+)/delete/$', post_delete, name="delete" ),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elan/models.py
from django.db import models


# Create your models here.
class Elan (models.Model):
    CATEGORY_CHOICES = (
    ('work','WORK'),
    ('kids', 'KIDS'),
    ('services','SERVICES'),
    ('education','EDUCATION'),
    ('personal','PPERSONAL'),
    ('apart','APART'),
    
    )
    user = models.ForeignKey('auth.User', related_name='elans')
    elanTitle = models.CharField(max_length=200)
    elanDescription = models.TextField()
    elanPrice = models.CharField(max_length=200)
    owner = models.CharField(max_length=200)
    ownerPhone = models.CharField(max_length=200)
    ownerMail = models.CharField(max_length=200, blank=True)
    ownerCity = models.CharField(max_length=30)
    itemCategory = models.CharField(max_length=200, choices = CATEGORY_CHOICES)
    image = models.FileField(null=True, blank=True)


    def __str__(self):
        return self.elanTitle

    def get_absolute_url(self):
        return reverse('elanlar:elandetail', kwargs={'id': self.id})    

class ElanComment(models.Model):
    elan = models.ForeignKey('elan.Elan', related_name='comments', on_delete=models.CASCADE)
    name= models.CharField(max_length=200, verbose_name="Ad")
    comment = models.TextField(verbose_name="Yorum")
    date = models.DateTimeField(auto_now_add=True)

class Subscribe(models.Model):
    mail = models.EmailField(max_length=100)

    def __str__(self):
        return self.mail

elan/forms.py
from .models import ElanComment,Elan
from django import forms

class CommentForm(forms.ModelForm):

    class Meta:
        model=ElanComment
        fields=[
            'name',
            'comment',

        ]
class ElanForm(forms.ModelForm):

    class Meta:
        model=Elan
        fields=[
            'elanTitle',
            'elanDescription',
            'elanPrice',
            'owner',
            'ownerPhone',
            'ownerMail',
            'ownerCity',
            'itemCategory',
            'image'
        ]                

elan/views.py
from django.shortcuts import render, get_object_or_404,redirect,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Elan, ElanComment
from .forms import CommentForm,ElanForm

def elan(request):
     items =  Elan.objects.all().order_by('-id')[:3]
     itemsmost = Elan.objects.all().order_by('-id')[3:4]
     kidsCategory = Elan.objects.all().filter(itemCategory="kids")[:6]
     eduCategory = Elan.objects.all().filter(itemCategory="education")[:6]
     workCategory = Elan.objects.all().filter(itemCategory="work")[:6]
     serviceCategory = Elan.objects.all().filter(itemCategory="service")[:6]
     personalCategory = Elan.objects.all().filter(itemCategory="service")[:6]
     apartCategory = Elan.objects.all().filter(itemCategory="service")[:6]
    

     context ={
         'items':items,
         'kidsCategory':kidsCategory,
         'eduCategory':eduCategory,
         'workCategory':workCategory,
         'serviceCategory': serviceCategory,
         
     }
     return render (request, 'elan/elanlar.html', context )

def elandetail(request, id):
    
    elan = get_object_or_404(Elan, id=id)
    form = CommentForm(request.POST or None)
   
    
    if form.is_valid():
        comment = form.save(commit=False)
        comment.elan = elan
        comment.save()
        
     
    items =  Elan.objects.all()[:4]
    comments= ElanComment.objects.all()  
    


    context ={
        'elan':elan,
        'form':form,
        'comments':comments,
        'items':items,
    }
    
    
    return render (request, 'elan/elandetail.html', context)

def store(request):
    itemsnew =  Elan.objects.all().order_by('-id')[:3]
    items =  Elan.objects.all()
    paginator = Paginator(items, 6)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
   
   
    context={
        'items':items,
        'itemsnew':itemsnew,
    }
    return render (request, 'elan/elans.html', context)

def kids (request):
   itemsnew =  Elan.objects.all().order_by('-id')[:3]
   items = Elan.objects.all().filter(itemCategory="kids")
   paginator = Paginator(items, 6)
   page = request.GET.get('page')

   try:
        items = paginator.page(page)
   except PageNotAnInteger:
        items = paginator.page(1)
   except EmptyPage:
        items = paginator.page(paginator.num_pages)
   
   
   context={
         'items':items,
        'itemsnew':itemsnew,
    }
   return render (request, 'elan/elans.html', context)

def work (request):
    itemsnew =  Elan.objects.all().order_by('-id')[:3]
    items =  Elan.objects.all().filter(itemCategory="work")
    paginator = Paginator(items, 6)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
   
    context={
        'items':items,
        'itemsnew':itemsnew,
    }
    return render (request, 'elan/elans.html', context)

def education (request):
    itemsnew =  Elan.objects.all().order_by('-id')[:3]
    items =  Elan.objects.all().filter(itemCategory="education")
    paginator = Paginator(items, 6)
    page = request.GET.get('page')
 
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages) 
   
    context={
        'items':items,
        'itemsnew':itemsnew,
    }
    return render (request, 'elan/elans.html', context)

def service (request):
    itemsnew =  Elan.objects.all().order_by('-id')[:3]
    items =  Elan.objects.all().filter(itemCategory="service")
    paginator = Paginator(items, 6)
    page = request.GET.get('page')
 
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
   
    context={
        'items':items,
        'itemsnew':itemsnew,
    }
    return render (request, 'elan/elans.html', context)

def personal (request):
    itemsnew =  Elan.objects.all().order_by('-id')[:3]
    items =  Elan.objects.all().filter(itemCategory="personal")
    paginator = Paginator(items, 6)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
   
    context={
        'items':items,
        'itemsnew':itemsnew,
    }
    return render (request, 'elan/elans.html', context)    

def apart (request):
    itemsnew =  Elan.objects.all().order_by('-id')[:3]
    items =  Elan.objects.all().filter(itemCategory="apart")
    paginator = Paginator(items, 6)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
   
    context={
        'items':items,
        'itemsnew':itemsnew,
    }
    return render (request, 'elan/elans.html', context)    


@login_required
def elanadmin(request):
   
    form = ElanForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
    items = Elan.objects.all()
    query = request.GET.get('q')
    if query:
       items = items.filter(elanTitle__icontains=query)
    paginator = Paginator(items, 6)
    page = request.GET.get('page')
    if not page:
        page = paginator.num_pages


   
   
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
   
    context = {
       
        'form':form,
        'items':items,
        
      }
    return render (request, 'elan/elancreate.html', context)    

@login_required
def elan_update(request, id):
    elan = get_object_or_404(Elan, id=id)
    form = ElanForm(request.POST or None, request.FILES or None, instance=elan)
    if form.is_valid():
        elan=form.save()
        return redirect('elanlar:elanadmin')
    context={
        'elan':elan
    }   
    return render (request, 'elan/elanupdate.html', context)

@login_required
def elan_delete(request,id):
    elan = get_object_or_404(Elan, id=id)
    elan.delete()
    return redirect('elanlar:elanadmin')

templates/elan/elanupdate.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
{% load crispy_forms_tags %}
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    LalaHelp
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
  <link href="/static/css/now-ui-dashboard.css?v=1.1.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <style>
.panel-header{
    background-image: url('https://cdn.dribbble.com/users/542624/screenshots/2799134/firewatch.png');

}
.panel-header-sm {
  height: 500px;
}

  </style>

</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="blue">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
    <div class="logo">
            <a href="http://www.creative-tim.com" class="simple-text logo-mini">
              LH
            </a>
            <a href="http://www.creative-tim.com" class="simple-text logo-normal">
             Admin
            </a>
          </div>
          <div class="sidebar-wrapper">
            <ul class="nav">
              <li>
                <a href="{% url 'blog:dashboard'%}">
                  <i class="fa fa-window-maximize"></i>
                  <p>Idare Paneli</p>
                </a>
              </li>
              <li>
                <a href="{% url 'blog:create'%}">
                  <i class="fa fa-edit"></i>
                  <p>Meqaleler</p>
                </a>
              </li>
              <li >
                <a href="fa fa-tasks">
                  <i class="fa fa-tasks"></i>
                  <p>Tapsiriqlar</p>
                </a>
              </li>
              <li>
                <a href="./notifications.html">
                  <i class="fa fa-bell"></i>
                  <p>Bildirisler</p>
                </a>
              </li>
              <li>
                <a href="./user.html">
                  <i class="fa fa-user"></i>
                  <p>User Profile</p>
                </a>
              </li>
             
            </ul>
          </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute bg-primary fixed-top">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#pablo">Maps</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
              <div class="input-group no-border">
               
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                  </div>
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'elanlar:main'%}">
                  <i class="fa fa-globe"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Sayta Bax</span>
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="now-ui-icons location_world"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="now-ui-icons users_single-02"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Account</span>
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="panel-header panel-header-sm">
      </div>
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
             
              </div>
              <div class="card-body ">
                <form method="POST" enctype="multipart/form-data">
                    {%csrf_token%}
                    
  
  <div id="div_id_elanTitle" class="form-group"> <label for="id_elanTitle" class="control-label  requiredField">
                  Elanın Adı<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_elanTitle" maxlength="200" name="elanTitle" type="text" value={{elan.elanTitle}}> </div> </div> <div id="div_id_elanDescription" class="form-group"> <label for="id_elanDescription" class="control-label  requiredField">
                  Elan Haqqında<span class="asteriskField">*</span> </label> <div class="controls "> <textarea class="textarea form-control" cols="40" id="id_elanDescription" name="elanDescription" rows="10">{{elan.elanDescription}}</textarea> </div> </div> <div id="div_id_elanPrice" class="form-group"> <label for="id_elanPrice" class="control-label  requiredField">
                  Qiymət<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_elanPrice" maxlength="200" name="elanPrice" type="text" value={{elan.elanPrice}}> </div> </div> <div id="div_id_owner" class="form-group"> <label for="id_owner" class="control-label  requiredField">
                  Elanın Sahibi<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_owner" maxlength="200" name="owner" type="text" value={{elan.owner}}> </div> </div> <div id="div_id_ownerPhone" class="form-group"> <label for="id_ownerPhone" class="control-label  requiredField">
                  Telefon<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_ownerPhone" maxlength="200" name="ownerPhone" type="text" value={{elan.ownerPhone}}> </div> </div> <div id="div_id_ownerMail" class="form-group"> <label for="id_ownerMail" class="control-label ">
                  Mail
              </label> <div class="controls "> <input class="textinput textInput form-control" id="id_ownerMail" maxlength="200" name="ownerMail" type="text" value={{elan.ownerMail}}> </div> </div> <div id="div_id_ownerCity" class="form-group"> <label for="id_ownerCity" class="control-label  requiredField">
                  Şəhər<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_ownerCity" maxlength="30" name="ownerCity" type="text" value={{elan.ownerCity}}> </div> </div> <div id="div_id_itemCategory" class="form-group"> <label for="id_itemCategory" class="control-label  requiredField">
                  Kategoriya<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_itemCategory" maxlength="200" name="itemCategory" type="text" value={{elan.itemCategory}}> </div> </div> <div id="div_id_image" class="form-group"> <button for="id_image" class="btn btn-primary ">
                  Şəkil
                  </button> <div class="controls "> <input class="clearablefileinput btn btn-primary" id="id_image" name="image" type="file" value={{elan.image}}> </div> </div>
  
                    
  
  
  
  
  
  
  <input type="submit" class="btn btn-primary">
        </form>
              </div>
            </div>
           
         

        </div>
      </div>
      
      <footer class="footer">
        <div class="container-fluid">
          <nav>
            <ul>
              <li>
                <a href="https://www.creative-tim.com">
                  Creative Tim
                </a>
              </li>
              <li>
                <a href="http://presentation.creative-tim.com">
                  About Us
                </a>
              </li>
              <li>
                <a href="http://blog.creative-tim.com">
                  Blog
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright">
            &copy;LalaHelp 
            <script>
              document.write(new Date().getFullYear())
            </script>
            by
            <a href="#" target="_blank">Rashid Maharramli</a>.
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
  <script src="/static/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
 
  <!--  Notifications Plugin    -->

  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/js/now-ui-dashboard.min.js" type="text/javascript"></script>
  <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
 
 
</body>

</html>