blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from post.views import home,post_index,blog,listing
from django.conf import settings 


from django.conf.urls.static import static 


urlpatterns = [
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', post_index, name="home"),
    url(r'^/blog', listing, name="blogpage"),
    url(r'post/', include('post.urls', namespace="blog")),
    url(r'accounts/', include('accounts.urls', namespace="accounts")),
    url(r'elan/', include('elan.urls', namespace="elanlar")),
  
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elan/urls.py
from django.conf.urls import include, url
from .views import *
from django.conf import settings 
from django.conf.urls.static import static 
app_name = "elan"
urlpatterns = [
   
    
    url(r'^main/',elan, name="main" ),
    url(r'^(?P<id>\d+)/$', elandetail, name="elandetail" ),
    url(r'^elanlar/', store, name="store" ),
    url(r'^kids/', kids, name="kids" ),
    url(r'^work/', work, name="work" ),
    url(r'^service/', service, name="service" ),
    url(r'^personal/', personal, name="personal" ),
    url(r'^apartment/', apart, name="apart" ),
    url(r'^education/', education, name="edu" ),
    url(r'^elanadmin/', elanadmin, name="elanadmin" ),
    url(r'^(?P<id>\d+)/update/$', elan_update, name="elanupdate" ),
    url(r'^(?P<id>\d+)/delete/$', elan_delete, name="elandelete" ),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import include, url
from .views import home,post_index,post_detail,adminpost,post_create,post_update,post_delete,contact
from django.conf import settings 
from django.conf.urls.static import static 
app_name = "blog"
urlpatterns = [
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^contact/', contact, name="index"),
    url(r'^(?P<id>\d+)/$', post_detail, name="detail" ),
    url(r'^dashboard/', adminpost, name="dashboard"),
    url(r'^create/', post_create, name="create"),
    url(r'^(?P<id>\d+)/update/$', post_update, name="update" ),
    url(r'^(?P<id>\d+)/delete/$', post_delete, name="delete" ),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models

from django.core.urlresolvers import reverse
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey('auth.user', verbose_name="Yazar",default=1)
    title = models.CharField(max_length=120)
    category = models.CharField(max_length=100, blank=True)
    description = models.TextField()
    source = models.CharField(max_length=300, blank=True)
    person = models.CharField(max_length=50, blank=True)
    published = models.DateField( auto_now_add=True)
    image = models.FileField(null=True, blank=True )
    tag = models.CharField(max_length=200, blank=True )
  


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'id': self.id})    

class Comment(models.Model):
    post = models.ForeignKey('post.Post', related_name='comments', on_delete=models.CASCADE)


    name= models.CharField(max_length=200, verbose_name="Ad")
    comment = models.TextField(verbose_name="Yorum")
    date = models.DateTimeField(auto_now_add=True)

class Contact(models.Model):
    ad = models.CharField(max_length=200)
    soyad = models.CharField(max_length=200)
    sual = models.CharField(max_length=600)

class Subscribe(models.Model):
    mail = models.EmailField(max_length=100)

    def __str__(self):
        return self.mail

templates/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    LalaHelp
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
  <link href="/static/css/now-ui-dashboard.css?v=1.1.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
<style>
.panel-header{
    background-image: url('https://cdn.dribbble.com/users/542624/screenshots/2799134/firewatch.png');

}
.panel-header-sm {
  height: 500px;
}

</style>
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="blue">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <a href="http://www.creative-tim.com" class="simple-text logo-mini">
          LH
        </a>
        <a href="http://www.creative-tim.com" class="simple-text logo-normal">
         Admin
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li>
            <a href="{% url 'blog:dashboard'%}">
              <i class="fa fa-window-maximize"></i>
              <p>Idare Paneli</p>
            </a>
          </li>
          <li>
            <a href="{% url 'blog:create'%}">
              <i class="fa fa-edit"></i>
              <p>Meqaleler</p>
            </a>
          </li>
          <li >
            <a href="{% url 'elanlar:elanadmin' %}">
              <i class="fa fa-tasks"></i>
              <p>Elanlar</p>
            </a>
          </li>
          <li>
            <a href="./notifications.html">
              <i class="fa fa-bell"></i>
              <p>Bildirisler</p>
            </a>
          </li>
          <li>
            <a href="./user.html">
              <i class="fa fa-user"></i>
              <p>User Profile</p>
            </a>
          </li>
         
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute bg-primary fixed-top">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#pablo">Maps</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
              <div class="input-group no-border">
                
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                  </div>
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:index'%}">
                        <i class="fa fa-globe"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Sayta Bax</span>
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="now-ui-icons location_world"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="now-ui-icons users_single-02"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Account</span>
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="panel-header panel-header-sm">
      </div>
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
                  
              </div>
              <div class="card-body ">
                
                 <div class="container">
                    <h2>Suallar</h2>
                    <p></p>            
                    <table class="table">
                      <thead>
                        <tr>
                          <th> ad </th>
                          <th>Email</th>
                          <th>sual</th>
                          
                          
                        </tr>
                      </thead>
                      <tbody>
                          {% for contact in contacts %}
                        <tr>
                          <td>{{contact.ad}}</td>
                          <td> {{contact.soyad}}</td>
                              <td>{{contact.sual}}</td>
                              
                        </tr>
                        
                               
                        
                        {% endfor %}
                       
                       
                      </tbody>
                    </table>


                 
                
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="card ">
                <div class="card-header ">
                    
                </div>
                <div class="card-body ">
                  
                   <div class="container">
                      <h2>Emails</h2>
                      <p></p>            
                      <table class="table">
                        <thead>
                          <tr>
                            <th> ad </th>
                           
                            
                            
                          </tr>
                        </thead>
                        <tbody>
                            {% for mail in mails %}
                          <tr>
                            <td>{{mail.mail}}</td>
                           
                                
                          </tr>
                          
                                 
                          
                          {% endfor %}
                         
                         
                        </tbody>
                      </table>
  
  
                   
                  
                </div>
              </div>
            </div>
          </div>
        </div>
        </div>
        
      <footer class="footer">
        <div class="container-fluid">
          <nav>
            <ul>
              <li>
                <a href="https://www.creative-tim.com">
                  Creative Tim
                </a>
              </li>
              <li>
                <a href="http://presentation.creative-tim.com">
                  About Us
                </a>
              </li>
              <li>
                <a href="http://blog.creative-tim.com">
                  Blog
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright">
            &copy; LalaHelp
            <script>
              document.write(new Date().getFullYear())
            </script> Created by
            <a href="https://www.invisionapp.com" target="_blank"> Rashid Maharramli</a>
            
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
 <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
  <script src="/static/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
 
  <!--  Notifications Plugin    -->

  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/js/now-ui-dashboard.min.js" type="text/javascript"></script>
  <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
</body>

</html>

templates/blog.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>lalahelpme</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="/static/vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="/static/vendor/font-awesome/css/font-awesome.min.css">
    <!-- Custom icon font-->
    <link rel="stylesheet" href="/static/css/fontastic.css">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Fancybox-->
    <link rel="stylesheet" href="/static/vendor/@fancyapps/fancybox/jquery.fancybox.min.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="/static/css/style.default.css" id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="/static/css/custom.css">
    <!-- Favicon-->
    <link rel="shortcut icon" href="favicon.png">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>
  <body>
    <header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-close"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">
                <form action="#">
                  <div class="form-group">
                    <input type="search" name="search" id="search" placeholder="What are you looking for?">
                    <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="#" class="navbar-brand">LalaHelpMe</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->
          <div id="navbarcollapse" class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a href="{% url 'home' %}" class="nav-link active ">Ana Səhifə</a>
                        </li>
                        <li class="nav-item"><a href="{% url 'blogpage' %}" class="nav-link ">Blog</a>
                        </li>
                        <li class="nav-item"><a href="{% url 'elanlar:main'%}" class="nav-link ">Elanlar</a>
                        </li>
                        <li class="nav-item"><a href="{% url 'blog:index' %}" class="nav-link ">Contact</a>
                        </li>
                      </ul>
                     
           
        </div>
      </nav>
    </header>
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              
          
             
              {% for post in posts %}
              <!-- post -->
              <div class="post col-xl-6">
                <div class="post-thumbnail"><a href="{% url 'blog:detail' post.id %}"><img src="/media/{{post.image}}" alt="..." class="img-responsive" width="300px" height="300px"></a></div>
                <div class="post-details">
                  <div class="post-meta d-flex justify-content-between">
                    <div class="date meta-last">{{post.published}}</div>
                    <div class="category"><a href="#">{{post.category}}</a></div>
                  </div><a href="{% url 'blog:detail' post.id %}">
                    <h3 class="h4">{{post.title}}</h3></a>
                  <p class="text-muted">{{post.description|truncatewords:7}}</p>
                  <div class="post-footer d-flex align-items-center"><a href="#" class="author d-flex align-items-center flex-wrap">
                      <div class="avatar"><img src="/static/img/lala.jpg" alt="..." class="img-fluid"></div>
                      <div class="title"><span>Lala</span></div></a>
                    <div class="date"><i class="fa fa-history"></i>{{post.published}}</div>
                    <div class="comments meta-last"><i class="fa fa-comment"></i>{{post.comments.count}}</div>
                  </div>
                </div>
               
            </div>
             {% endfor %}
              </div>
            <!-- Pagination -->
            {% if posts.has_other_pages %}
            <ul class="pagination">
              {% if posts.has_previous %}
                <li><a class="btn btn-primary" href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
              {% else %}
                <li class="disabled  btn btn-primary"><span>&laquo;</span></li>
              {% endif %}
              {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                  <li class="active btn btn-primary"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                  <li><a class="btn btn-primary "href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
              {% endfor %}
              {% if posts.has_next %}
                <li><a class="btn btn-primary" href="?page={{ posts.next_page_number }}">&raquo;</a></li>
              {% else %}
                <li class="disabled btn btn-primary"><span>&raquo;</span></li>
              {% endif %}
            </ul>
          {% endif %}
          </div>
        </main>
        <aside class="col-lg-4">
                <!-- Widget [Search Bar Widget]-->
                <div class="widget search">
                  <header>
                    <h3 class="h6">Axtar</h3>
                  </header>
                  <form  class="search-form" role="search" method="GET" action="">
                    <div class="form-group">
                      <input type="text" name="q" placeholder="Məqalə Axtar">
                      <button type="submit" class="submit"><i class="fa fa-search"></i></button>
                    </div>
                  </form>
                </div>
                <!-- Widget [Latest Posts Widget]        -->
                <div class="widget latest-posts">
                  <header>
                    <h3 class="h6">Meqalələrdən</h3>
                  </header>
                  {% for post in postss %}
                  <div class="blog-posts"><a href="{% url 'blog:detail' post.id %}">
                      <div class="item d-flex align-items-center">
                        <div class="image"><img src="/media/{{post.image}}" alt="..." class="img-fluid"></div>
                        <div class="title"><strong>{{post.title}}</strong>
                          <div class="d-flex align-items-center">
                            
                            <div class="comments"><i class="	fa fa-comment"></i>{{post.comments.count}}</div>
                          </div>
                        </div>
                        
                      </div></a></div>
                      {% endfor %}
                </div>
            
                <!-- Widget [Categories Widget]-->
                <div class="widget categories">
                  <header>
                    <h3 class="h6">Kateqoriyalar</h3>
                  
                  <div class="item d-flex justify-content-between"><a href="#">Məqalə</a><span></span></div>
                  <div class="item d-flex justify-content-between"><a href="#">Təhsil</a><span></span></div>
                  <div class="item d-flex justify-content-between"><a href="#">Təbiət</a><span></span></div>
                
                </div>
                <!-- Widget [Tags Cloud Widget]-->
                <div class="widget tags">       
                  <header>
                    <h3 class="h6">Tags</h3>
                  </header>
                  <ul class="list-inline">
                    <li class="list-inline-item"><a href="#" class="tag">#təbiətgözəldir</a></li>
                    <li class="list-inline-item"><a href="#" class="tag">#təhsilönəmlidir</a></li>
                    <li class="list-inline-item"><a href="#" class="tag">#sədəqəverin</a></li>
                  </ul>
                </div>
              </aside>
      </div>
    </div>
    <!-- Page Footer-->
    <footer class="main-footer">
            <div class="container">
              <div class="row">
                <div class="col-md-4">
                  <div class="logo">
                    <h6 class="text-white">LalaContact</h6>
                  </div>
                  <div class="contact-details">
                    <p>Email: lalahelpinfo@gmail.com</p>
                    <ul class="social-menu">
                      <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                      <li class="list-inline-item"><a href="instagram.com"><i class="fa fa-instagram"></i></a></li>
                     
                    </ul>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="menus d-flex">
                    <ul class="list-unstyled">
                      <li> <a href="#">Blog</a></li>
                      <li> <a href="#">Elanlar</a></li>
                      <li> <a href="#">Contact</a></li>
                      <li> <a href="#">Privacy &amp; Policy</a></li>
                    </ul>
                    </ul>
                    
                  </div>
                </div>
              
              </div>
            </div>
            <div class="copyrights">
              <div class="container">
                <div class="row">
                  <div class="col-md-6">
                    <p>&copy; 2018. | Bütün hüquqlar qorunur.</p>
                  </div>
                  <div class="col-md-6 text-right">
                    <p>Created by <a href="#" class="text-white">Rashid Maharramli</a>
                      <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </footer>
    <!-- Javascript files-->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"> </script>
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/vendor/jquery.cookie/jquery.cookie.js"> </script>
    <script src="/static/vendor/@fancyapps/fancybox/jquery.fancybox.min.js"></script>
    <script src="/static/js/front.js"></script>
  </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load crispy_forms_tags%}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LalaHelp</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom styles for this template -->
    <link href="/static/css/home.css" rel="stylesheet">
    <style>
    .overlay{
        background-image:url('https://images4.alphacoders.com/232/thumb-1920-232854.jpg');
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;

    }
    .bg-light {
    background-color: transparent !important;
}
.navbar-light .navbar-brand {
    color: #ffffff;
}

#flashMessage {
    color: white;
    background-color: #28bd4f;
    padding: 15px;
    border-radius: 5px;
    display: block;
    width: calc(100% - 100px);
    margin-bottom: 40px;
  	position: absolute;
}

    </style>
   
    
  </head>

  <body>

    <div class="overlay"></div>
    
   

    <div class="masthead">
      <div class="masthead-bg"></div>
      <div class="container h-100">
        

        <div class="row h-100">
            
          <div class="col-12 my-auto">
            
             
            <div class="masthead-content text-white py-5 py-md-0">
                
              <h1 class="mb-3">LalaHelpMe</h1>
              <p class="mb-5">Buradan sual soruşa bilərsiniz
                <strong></strong></p>
              <div class="input-group input-group-newsletter">
                  <form method="POST">
                        {% csrf_token %}                      
     
     <div id="div_id_ad" class="form-group"> <label for="id_ad" class="control-label  requiredField">
                     Ad Soyad<span class="asteriskField"></span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_ad" maxlength="200" name="ad" type="text"> </div> </div> <div id="div_id_soyad" class="form-group"> <label for="id_soyad" class="control-label  requiredField">
                     Email<span class="asteriskField"></span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_soyad" maxlength="200" name="soyad" type="text"> </div> </div> <div id="div_id_sual" class="form-group"> <label for="id_sual" class="control-label  requiredField">
                     Sual<span class="asteriskField"></span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_sual" maxlength="600" name="sual" type="text"> </div> </div>
                      <button id="send" class="btn btn-secondary" type="submit">Soruş</button>
                      
                      
                      </form>
                     
                      
                <div class="input-group-append">
                  
                  
                </div>
              </div>
            </div>
          </div>
          
        </div>
        
      </div>
    </div>
 
    

    <div class="social-icons">
      <ul class="list-unstyled text-center mb-0">
        <li class="list-unstyled-item">
          <a href="{% url 'blog:dashboard' %}">
            <i class="fa fa-user"></i>
          </a>
        </li>
        <li class="list-unstyled-item">
         <a href="{% url 'blogpage' %}">
            <i class="fa fa-globe"></i>
          </a>
        </li>
        <li class="list-unstyled-item">
          <a href="https://www.instagram.com/gulallahinqulu/">
            <i class="fa fa-instagram"></i>
          </a>
        </li>
      </ul>
    </div>

    <!-- Bootstrap core JavaScript -->
    <script src="/static/js/jquery.min.js"></script>
   

    <!-- Custom scripts for this template -->
   
    

  </body>
  

</html>