blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from post.views import home,post_index,blog,listing
from django.conf import settings 


from django.conf.urls.static import static 


urlpatterns = [
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', post_index, name="home"),
    url(r'^/blog', listing, name="blogpage"),
    url(r'post/', include('post.urls', namespace="blog")),
    url(r'accounts/', include('accounts.urls', namespace="accounts")),
    url(r'elan/', include('elan.urls', namespace="elanlar")),
  
    
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

elan/urls.py
from django.conf.urls import include, url
from .views import *
from django.conf import settings 
from django.conf.urls.static import static 
app_name = "elan"
urlpatterns = [
   
    
    url(r'^main/',elan, name="main" ),
    url(r'^(?P<id>\d+)/$', elandetail, name="elandetail" ),
    url(r'^elanlar/', store, name="store" ),
    url(r'^kids/', kids, name="kids" ),
    url(r'^work/', work, name="work" ),
    url(r'^service/', service, name="service" ),
    url(r'^personal/', personal, name="personal" ),
    url(r'^apartment/', apart, name="apart" ),
    url(r'^education/', education, name="edu" ),
    url(r'^elanadmin/', elanadmin, name="elanadmin" ),
    url(r'^(?P<id>\d+)/update/$', elan_update, name="elanupdate" ),
    url(r'^(?P<id>\d+)/delete/$', elan_delete, name="elandelete" ),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import include, url
from .views import home,post_index,post_detail,adminpost,post_create,post_update,post_delete,contact
from django.conf import settings 
from django.conf.urls.static import static 
app_name = "blog"
urlpatterns = [
    # Examples:
    # url(r'^$', 'blog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^contact/', contact, name="index"),
    url(r'^(?P<id>\d+)/$', post_detail, name="detail" ),
    url(r'^dashboard/', adminpost, name="dashboard"),
    url(r'^create/', post_create, name="create"),
    url(r'^(?P<id>\d+)/update/$', post_update, name="update" ),
    url(r'^(?P<id>\d+)/delete/$', post_delete, name="delete" ),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models

from django.core.urlresolvers import reverse
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey('auth.user', verbose_name="Yazar",default=1)
    title = models.CharField(max_length=120)
    category = models.CharField(max_length=100, blank=True)
    description = models.TextField()
    source = models.CharField(max_length=300, blank=True)
    person = models.CharField(max_length=50, blank=True)
    published = models.DateField( auto_now_add=True)
    image = models.FileField(null=True, blank=True )
    tag = models.CharField(max_length=200, blank=True )
  


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'id': self.id})    

class Comment(models.Model):
    post = models.ForeignKey('post.Post', related_name='comments', on_delete=models.CASCADE)


    name= models.CharField(max_length=200, verbose_name="Ad")
    comment = models.TextField(verbose_name="Yorum")
    date = models.DateTimeField(auto_now_add=True)

class Contact(models.Model):
    ad = models.CharField(max_length=200)
    soyad = models.CharField(max_length=200)
    sual = models.CharField(max_length=600)

class Subscribe(models.Model):
    mail = models.EmailField(max_length=100)

    def __str__(self):
        return self.mail

post/forms.py
from django import forms
from .models import Post, Comment, Contact, Subscribe

class PostForm(forms.ModelForm):

    class Meta:
        model=Post
        fields=[
            'title',
            'category',
            'description',
            'tag',
            'source',
            'person',
            'image',
            

        ]
class CommentForm(forms.ModelForm):

    class Meta:
        model=Comment
        fields=[
            'name',
            'comment',

        ]
                
class ContactForm(forms.ModelForm):
     class Meta:
          model=Contact
          fields=[
              'ad',
              'soyad',
              'sual',
          ]
          
class EmailForm(forms.ModelForm):
    class Meta:
        model=Subscribe
        fields=[
            'mail'
        ]

post/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Post,Comment,Contact,Subscribe
from .forms import PostForm, CommentForm, ContactForm, EmailForm
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F
# Create your views here.
def home(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
    context={
        'form':form,
    } 
    

    return render (request, 'home.html' ,context)

def blog(request):
    posts = Post.objects.all()
    return render (request, 'blog.html', {"posts":posts})    


def post_index(request):
    form = EmailForm(request.POST or None)
    if form.is_valid():
        mail = form.save()
        return redirect ('home')
   
  
    posts = Post.objects.all().order_by('-id')[:3]
    return render (request, 'index.html', {"posts":posts, 'form':form})    

def post_detail(request, id):
    post = get_object_or_404(Post, id=id)
    posts = Post.objects.all().order_by('-id')[:3]
    postss= Post.objects.all().order_by('-published')[1:4]
    form = CommentForm(request.POST or None)
   
    
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return redirect (post.get_absolute_url())

    comments= Comment.objects.all().count()   


    context = {
        'post':post,
        'form':form,
        'posts':posts,
        'comments':comments,  
        'postss':postss,    
        }
    return render (request, 'post/detail.html', context )
def contact (request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
    context={
        'form':form,
    }    
    return render (request, 'home.html',context)


@login_required
def adminpost(request):
   
    contacts = Contact.objects.all()
    mails = Subscribe.objects.all()
    context = {
       
        'contacts':contacts,
        'mails':mails,
      }
    return render (request, 'admin.html', context)
@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    posts = Post.objects.all()
    if form.is_valid():
        post = form.save()
  
    paginator = Paginator(posts, 8)
    page = request.GET.get('page')
    if not page:
        page = paginator.num_pages
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
        
        
    context={
        'form':form,
        'posts':posts,
    }
    return render (request, 'post/meqale.html',context)
@login_required
def post_update(request, id):
    post = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        post = form.save()
        return redirect ('blog:create')
      
    context = {
        'post':post,
      }
    return render (request, 'post/update_post.html', context )

@login_required
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect ('blog:create')



def listing(request): 
   posts = Post.objects.all()
   
   postss= Post.objects.all().order_by('-published')[4:8]
   query = request.GET.get('q')
   if query:
       posts = posts.filter(title__icontains=query)
   paginator = Paginator(posts, 8)
   page = request.GET.get('page')
   if not page:
    page = paginator.num_pages


   
   
   try:
        posts = paginator.page(page)
   except PageNotAnInteger:
        posts = paginator.page(1)
   except EmptyPage:
        posts = paginator.page(paginator.num_pages)
   

   return render(request, 'blog.html', { 'posts':posts , 'postss':postss})

templates/post/comment.html
{% load crispy_forms_tags %}

<form method="POST">
{% csrf_token%}
{{form|crispy}}
<input type="submit" class="btn btn-primary">
</form>

templates/post/meqale.html
<!DOCTYPE html>
<html lang="en">
{% load static%}
{% load crispy_forms_tags %}
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    LalaHelp
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- CSS Files -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
  <link href="/static/css/now-ui-dashboard.css?v=1.1.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <style>
.panel-header{
    background-image: url('https://cdn.dribbble.com/users/542624/screenshots/2799134/firewatch.png');

}
.panel-header-sm {
  height: 500px;
}

  </style>

</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="blue">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
    <div class="logo">
            <a href="http://www.creative-tim.com" class="simple-text logo-mini">
              LH
            </a>
            <a href="http://www.creative-tim.com" class="simple-text logo-normal">
             Admin
            </a>
          </div>
          <div class="sidebar-wrapper">
            <ul class="nav">
              <li>
                <a href="{% url 'blog:dashboard'%}">
                  <i class="fa fa-window-maximize"></i>
                  <p>Idare Paneli</p>
                </a>
              </li>
              <li>
                <a href="{% url 'blog:create'%}">
                  <i class="fa fa-edit"></i>
                  <p>Meqaleler</p>
                </a>
              </li>
              <li >
                <a href="{% url 'elanlar:elanadmin' %}">
                  <i class="fa fa-tasks"></i>
                  <p>Elanlar</p>
                </a>
              </li>
              <li>
                <a href="./notifications.html">
                  <i class="fa fa-bell"></i>
                  <p>Bildirisler</p>
                </a>
              </li>
              <li>
                <a href="./user.html">
                  <i class="fa fa-user"></i>
                  <p>User Profile</p>
                </a>
              </li>
             
            </ul>
          </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent  navbar-absolute bg-primary fixed-top">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#pablo">Maps</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
               <!--SEARCH BAR -->
            <form role="search" method="GET" action="">
              <div class="form-group row">
                <input type="text" class="form-control col-sm-9"name="q" placeholder="Məqalə Axtar">
                <button class="btn btn-primary col-sm-3"type="submit" class="submit"><i class="fa fa-search"></i></button>
              </div>
            </form>

            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:index'%}">
                  <i class="fa fa-globe"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Sayta Bax</span>
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="now-ui-icons location_world"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="now-ui-icons users_single-02"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Account</span>
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="panel-header panel-header-sm">
      </div>
      <div class="content">
        <div class="row">
          <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
             
              </div>
              <div class="card-body ">
                <form method="POST" enctype="multipart/form-data">
                  {%csrf_token%}
                  

<div id="div_id_title" class="form-group"> <label for="id_title" class="control-label  requiredField">
      Başlıq<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_title" maxlength="120" name="title" type="text"> </div> </div> <div id="div_id_category" class="form-group"> <label for="id_category" class="control-label ">
      Kateqoriya
  </label> <div class="controls "> <input class="textinput textInput form-control" id="id_category" maxlength="100" name="category" type="text"> </div> </div> <div id="div_id_description" class="form-group"> <label for="id_description" class="control-label  requiredField">
      Məqalə<span class="asteriskField">*</span> </label> <div class="controls "> <textarea class="textarea form-control" cols="40" id="id_description" name="description" rows="10"></textarea> </div> </div> <div id="div_id_tag" class="form-group"> <label for="id_tag" class="control-label  requiredField">
        Tag<span class="asteriskField">*</span> </label> <div class="controls "> <input class="textinput textInput form-control" id="id_tag" maxlength="120" name="tag" type="text"> </div> </div><div id="div_id_source" class="form-group"> <label for="id_source" class="control-label ">
      Önəmli Hissə (Məsələn Yunus Əmrədən bir şeir)
  </label> <div class="controls "> <input class="textinput textInput form-control" id="id_source" maxlength="300" name="source" type="text"> </div> </div> <div id="div_id_person" class="form-group"> <label for="id_person" class="control-label ">
      Şəxs (Önəmli Hissəni deyən)
  </label> <div class="controls "> <input class="textinput textInput form-control" id="id_person" maxlength="50" name="person" type="text"> </div> </div> <div id="div_id_image" class="form-group"> <button for="id_image" class="btn btn-primary ">
      Şəkil
  </button> <div class="controls "> <input class="clearablefileinput" id="id_image" name="image" type="file"> </div> </div>




<input type="submit" class="btn btn-primary">
      </form>
              </div>
            </div>
            <div class="col-md-12">
                    <div class="card ">
                      <div class="card-header ">
                       Admin
                      </div>
                      <div class="card-body ">
                            <div class="container">
                                    <h2>Meqaleler</h2>
                                    <p>Burda Redakte Etmek olar, ve Meqaleleri silmek olar</p>            
                                    <table class="table">
                                      <thead>
                                        <tr>
                                          <th>Basliq</th>
                                          
                                          
                                        </tr>
                                      </thead>
                                      <tbody>
                                            {% for post in posts %}
                                        <tr>
                                          <td>{{post.title}}</td>
                                          <td> <a href="{% url 'blog:update' post.id %}">
                                                <i class="fa fa-edit"></i>
                                               
                                              </a> </td>
                                              <td>
                                                    <a href="{% url 'blog:delete' post.id %}">
                                                            <i class="fa fa-trash"></i>
            
                                              </td>
                                          
                                        </tr>
                                        
                                               
                                        
                                        {% endfor %}
                                       
                                       
                                      </tbody>
                                    </table>
                                  </div>
                      </div>
                    </div>
          </div>

          <!-- Pagination -->
          {% if posts.has_other_pages %}
          <ul class="pagination">
            {% if posts.has_previous %}
              <li><a class="btn btn-primary" href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled  btn btn-primary"><span>&laquo;</span></li>
            {% endif %}
            {% for i in posts.paginator.page_range %}
              {% if posts.number == i %}
                <li class="active btn btn-primary"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a class="btn btn-primary "href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if posts.has_next %}
              <li><a class="btn btn-primary" href="?page={{ posts.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled btn btn-primary"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
          

        </div>
      </div>
      
      <footer class="footer">
        <div class="container-fluid">
          <nav>
            <ul>
              <li>
                <a href="https://www.creative-tim.com">
                  Creative Tim
                </a>
              </li>
              <li>
                <a href="http://presentation.creative-tim.com">
                  About Us
                </a>
              </li>
              <li>
                <a href="http://blog.creative-tim.com">
                  Blog
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright">
            &copy;LalaHelp 
            <script>
              document.write(new Date().getFullYear())
            </script>
            by
            <a href="#" target="_blank">Rashid Maharramli</a>.
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/js/popper.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
  <script src="/static/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chart JS -->
 
  <!--  Notifications Plugin    -->

  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="/static/js/now-ui-dashboard.min.js" type="text/javascript"></script>
  <!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
 
 
</body>

</html>